# Generated by Django 2.0.7 on 2018-07-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_pb3', '0002_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete='', related_name='worked_jobs', to='tasks_pb3.User'),
        ),
    ]
